FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
COPY patch_chart.py .
COPY patch_v04_backend.py .
COPY patch_v04_frontend.py .
COPY patch_v05_filters.py .
COPY patch_v06_backend.py .
COPY patch_v06_frontend.py .
RUN python patch_chart.py
RUN python patch_v04_backend.py
RUN python patch_v04_frontend.py
RUN python patch_v05_filters.py
RUN python patch_v06_backend.py
RUN python patch_v06_frontend.py
EXPOSE 8890
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","8890"]
