from pathlib import Path

p=Path('/app/app.py') if Path('/app/app.py').exists() else Path('app.py')
s=p.read_text(encoding='utf-8')
s=s.replace('version="0.5.0"','version="0.6.0"').replace('"version": "0.5.0"','"version": "0.6.0"').replace('台股研究版 v0.5','台股研究版 v0.6')
s=s.replace('d["MA20"] = d["Close"].rolling(20).mean()\n        d["VMA20"] = d["Volume"].rolling(20).mean()','d["MA20"] = d["Close"].rolling(20).mean()\n        d["MA60"] = d["Close"].rolling(60).mean()\n        d["VMA20"] = d["Volume"].rolling(20).mean()')
old='''        trend20 = (close / float(d.iloc[-21]["Close"]) - 1) * 100\n        score = 50 + min(volume_ratio, 5) * 8 + max(0, 20 - proximity * 800) + max(0, min(trend20, 20))\n        if first_pullback:\n            score += 15\n        return {\n            "symbol": code, "name": POPULAR.get(code, code), "ticker": ticker,\n            "last": _f(close), "ma20": _f(ma20), "distance_ma20_pct": _f((close / ma20 - 1) * 100),\n            "surge_date": pd.Timestamp(surge_idx).strftime("%Y-%m-%d"), "volume_ratio": _f(volume_ratio),\n            "trend20_pct": _f(trend20), "first_pullback": first_pullback, "score": _f(score, 1),\n        }'''
new='''        trend20 = (close / float(d.iloc[-21]["Close"]) - 1) * 100\n        ma20_old = float(d["MA20"].iloc[-6]) if pd.notna(d["MA20"].iloc[-6]) else ma20\n        ma20_slope_pct = (ma20 / ma20_old - 1) * 100 if ma20_old else 0\n        ma60 = float(latest["MA60"]) if pd.notna(latest["MA60"]) else None\n        above_ma60 = bool(ma60 and close > ma60)\n        surge_low = float(surge_row["Low"])\n        structure_intact = close > surge_low\n        latest_volume = float(latest["Volume"]) if pd.notna(latest["Volume"]) else 0\n        surge_volume = float(surge_row["Volume"]) if pd.notna(surge_row["Volume"]) else 0\n        shrink = (1 - latest_volume / surge_volume) * 100 if surge_volume else 0\n        days_since_surge = max(0, len(d.loc[surge_idx:]) - 1)\n        risk_pct = max(0, (close - surge_low) / close * 100) if close else 0\n        score = min(100, max(0, min(volume_ratio/3,1)*20 + max(0,1-proximity/0.025)*20 + (15 if ma20_slope_pct>0 else 0) + (10 if above_ma60 else 0) + (15 if shrink>=30 else (8 if shrink>0 else 0)) + (15 if first_pullback else 0) + (5 if structure_intact else 0)))\n        grade = "A" if score>=80 else ("B" if score>=65 else ("C" if score>=50 else "D"))\n        reasons=[f"爆量{volume_ratio:.1f}倍",f"{days_since_surge}天前","MA20上彎" if ma20_slope_pct>0 else "MA20未上彎",f"回測量縮{shrink:.0f}%" if shrink>0 else "回測未量縮"]\n        if first_pullback: reasons.append("首次回測")\n        if above_ma60: reasons.append("站上MA60")\n        if not structure_intact: reasons.append("結構已破壞")\n        return {\n            "symbol": code, "name": POPULAR.get(code, code), "ticker": ticker,\n            "last": _f(close), "ma20": _f(ma20), "ma60": _f(ma60), "distance_ma20_pct": _f((close / ma20 - 1) * 100),\n            "surge_date": pd.Timestamp(surge_idx).strftime("%Y-%m-%d"), "days_since_surge": days_since_surge, "volume_ratio": _f(volume_ratio),\n            "pullback_volume_shrink_pct": _f(shrink), "trend20_pct": _f(trend20), "ma20_slope_pct": _f(ma20_slope_pct), "above_ma60": above_ma60,\n            "first_pullback": first_pullback, "structure_intact": structure_intact, "invalidation_price": _f(surge_low), "risk_to_stop_pct": _f(risk_pct),\n            "score": _f(score,1), "quality_grade": grade, "reasons": reasons,\n        }'''
if old not in s: raise SystemExit('scanner block not found')
s=s.replace(old,new)
s=s.replace('"第一次回測": "爆量日之後尚未出現過相同20MA回測條件"','"第一次回測": "爆量日之後尚未出現過相同20MA回測條件", "品質分數": "量能20 + MA20距離20 + MA20趨勢15 + MA60位置10 + 回測量縮15 + 首次回測15 + 結構完整5", "失效價": "最近一次爆量上漲K棒低點"')
p.write_text(s,encoding='utf-8',newline='\n')
print('v0.6 backend patch applied')
